spring:
  zipkin:
    base-url: http://maf-zipkin-production:9411
  devtools:
    add-properties: false
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://maf-mysql-server-master-production:3306/muscle_and_fitness?useSSL=true&useUnicode=true
          username: maf_mysql_rw
          password: maf@mysql
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave1:
          url: jdbc:mysql://maf-mysql-server-slave-production:3306/muscle_and_fitness?useSSL=true&useUnicode=true
          username: maf_mysql_r
          password: maf@mysql
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: maf-redis-production
    port: 6379
    password: maf@redis
  rabbitmq:
    host: maf-rabbitmq-production
    port: 5672
    username: maf_rabbitmq_su
    password: maf@rabbitmq

maf:
  configuration:
    swagger-enabled: true

minio:
  endpoint: http://maf-minio-production
  port: 9000
  access-key: maf_minio_root_user
  secret-key: jm@minio
  bucket-name: maf
