spring:
  zipkin:
    base-url: http://maf-zipkin-development-docker:9411
  devtools:
    add-properties: true
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://maf-mysql-server-master-development-docker:3306/muscle_and_fitness?useSSL=true&useUnicode=true
          username: maf_mysql_rw
          password: maf@mysql
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave1:
          url: jdbc:mysql://maf-mysql-server-slave-development-docker:3306/muscle_and_fitness?useSSL=true&useUnicode=true
          username: maf_mysql_r
          password: maf@mysql
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: maf-redis-development-docker
    port: 6379
    password: maf@redis
  rabbitmq:
    host: maf-rabbitmq-development-docker
    port: 5672
    username: maf_rabbitmq_su
    password: maf@rabbitmq

maf:
  configuration:
    swagger-enabled: true

minio:
  endpoint: http://maf-minio-development-docker
  port: 9000
  access-key: maf_minio_root_user
  secret-key: jm@minio
  bucket-name: maf
