spring:
  datasource:
    url: jdbc:mysql://localhost:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: root
    password: jm@mysql
  devtools:
    add-properties: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
