spring:
  datasource:
    url: jdbc:mysql://maf.mysql.test:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: root
    password: jm@mysql
  devtools:
    add-properties: false

eureka:
  client:
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:${server.port}/eureka/
