spring:
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://localhost:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: root
    password: jm@mysql
  redis:
    host: localhost
    port: 6379
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/

sftp:
  client:
    configuration:
      host: localhost
      port: 23
      user: johnny
      password: atmoz@sftp
