server:
  port: @service-registry.port@
  tomcat:
    uri-encoding: @project.build.sourceEncoding@

spring:
  application:
    name: @project.artifactId@
  profiles:
    active: @env@
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Hong_Kong

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  config: classpath:configuration/logback/logback-@env@.xml
  # Configure logging level of project as DEBUG to enable SQL logging and other logging.
  level:
    com.jmsoftware: DEBUG

project:
  property:
    base-package: com.jmsoftware.maf.serviceregistry
    context-path:
    group-id: @project.groupId@
    parent-artifact-id: @project.parent.artifactId@
    project-artifact-id: @project.artifactId@
    version: @project.version@
    description: @project.description@
    jdk-version: @java.version@
    environment: @env@
    environment-alias: @envAlias@
    url: @project.url@
    inception-year: @inceptionYear@
    organization-name: @project.organization.name@
    organization-url: @project.organization.url@
    issue-management-system: @project.issueManagement.system@
    issue-management-url: @project.issueManagement.url@
    developer-name: @developerName@
    developer-email: @developerEmail@
    developer-url: @developerUrl@
