server:
  port: @service-registry.port@
  tomcat:
    uri-encoding: @project.build.sourceEncoding@

spring:
  application:
    name: @project.artifactId@
  profiles:
    active: @env@
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Hong_Kong

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  config: classpath:configuration/logback/logback-@env@.xml

maf:
  project-property:
    base-package: @project.groupId@
    context-path:
    group-id: @project.groupId@
    project-parent-artifact-id: @project.parent.artifactId@
    project-artifact-id: @project.artifactId@
    version: @project.version@
    description: @project.description@
    jdk-version: @java.version@
    environment: ${spring.profiles.active}
    url: @project.url@
    inception-year: @inceptionYear@
    organization-name: @project.organization.name@
    organization-url: @project.organization.url@
    issue-management-system: @project.issueManagement.system@
    issue-management-url: @project.issueManagement.url@
    developer-name: @developerName@
    developer-email: @developerEmail@
    developer-url: @developerUrl@
  configuration:
    ignored-url:
      pattern:
        - "/actuator/**"
    included-package-for-http-api-scan: ${project.property.base-package}
    swagger-disabled: true
