kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: maven:3-jdk-11
    commands:
      - mvn clean install --batch-mode --show-version -DskipTests=true -Dmaven.javadoc.skip=true
