spring:
  devtools:
    add-properties: true
  zipkin:
    base-url: http://localhost:9411
  redis:
    host: localhost
    port: 6379
    password: maf@redis

maf:
  configuration:
    web-security-enabled: false
