spring:
  devtools:
    add-properties: true
  zipkin:
    base-url: http://localhost:9411

redis:
  master:
    host: localhost
    port: 6379
    password: maf@redis
  slaves:
    - host: localhost
      port: 6380
      password: maf@redis

maf:
  configuration:
    web-security-enabled: true
