eureka:
  client:
    serviceUrl:
      defaultZone: http://maf.service-registry.development:8760/eureka/

spring:
  zipkin:
    base-url: http://maf.zipkin.development:9411
  devtools:
    add-properties: true
