eureka:
  client:
    serviceUrl:
      defaultZone: http://maf.service-registry.stage:8760/eureka/

spring:
  zipkin:
    base-url: http://maf.zipkin.stage:9411
  devtools:
    add-properties: false
