spring:
  zipkin:
    base-url: http://localhost:9411
  devtools:
    add-properties: true
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/muscle_and_fitness?useSSL=true&useUnicode=true
          username: maf_mysql_rw
          password: maf@mysql
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave1:
          url: jdbc:mysql://localhost:3307/muscle_and_fitness?useSSL=true&useUnicode=true
          username: maf_mysql_r
          password: maf@mysql
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: maf@redis
  rabbitmq:
    host: localhost
    port: 5672
    username: maf_rabbitmq_su
    password: maf@rabbitmq

sftp:
  host: localhost
  port: 23
  user: johnny
  password: atmoz@sftp

maf:
  configuration:
    swagger-enabled: false
