spring:
  zipkin:
    base-url: http://maf-zipkin:9411
  devtools:
    add-properties: false
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://maf-mysql-server-master:3306/muscle_and_fitness?useSSL=true&useUnicode=true
          username: maf_mysql_rw
          password: maf@mysql
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave1:
          url: jdbc:mysql://maf-mysql-server-slave:3306/muscle_and_fitness?useSSL=true&useUnicode=true
          username: maf_mysql_r
          password: maf@mysql
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: maf-redis
    port: 6379
    password: maf@redis
  rabbitmq:
    host: maf-rabbitmq
    port: 5672
    username: maf_rabbitmq_su
    password: maf@rabbitmq

maf:
  configuration:
    swagger-enabled: false
