server:
  port: @exercise-mis.port@
  tomcat:
    uri-encoding: @project.build.sourceEncoding@

spring:
  application:
    name: @project.artifactId@
  profiles:
    active: @env@
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Hong_Kong
  sleuth:
    sampler:
      probability: 1.0
  servlet:
    multipart:
      # `location` specifies the directory where uploaded files will be stored. When not specified,
      # a temporary directory will be used. ATTENTION: it may differ due to OS.
      location: ~/Documents/@project.parent.artifactId@/@project.artifactId@/temprary-file
      # `max-file-size` specifies the maximum size permitted for uploaded files. The default is 1MB. We set it as 64 MB.
      max-file-size: 64MB
      # `max-request-size` specifies the maximum size allowed for multipart/form-data requests. The default is 10MB.
      max-request-size: 70MB
      # `file-size-threshold` specifies the size threshold after which files will be written to disk.
      # The default is 0. We set it as 0 too.
      file-size-threshold: 0
  datasource:
    name: muscle_and_fitness
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: -1ms
        min-idle: 0

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    status-page-url-path: /
    metadata-map:
      # needed to trigger info and endpoint update after restart
      startup: ${random.int}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}@${spring.cloud.client.hostname}@${spring.application.name}-${random.int}
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
  compression:
    request:
      enabled: true
    response:
      enabled: true
      useGzipDecoder: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mapper-locations should start with `classpath*` prefix
  # when project is based on Maven multi-module to load XML mapper in different jar
  mapper-locations: classpath*:/mapper/**/*Mapper.xml

logging:
  config: classpath:configuration/logback/logback-@env@.xml
  level:
    # Configure logging level for SFTP/JSCH
    com.jcraft.jsch: INFO

maf:
  project-property:
    base-package: @project.groupId@
    context-path:
    group-id: @project.groupId@
    project-parent-artifact-id: @project.parent.artifactId@
    project-artifact-id: @project.artifactId@
    version: @project.version@
    description: @project.description@
    jdk-version: @java.version@
    environment: @env@
    url: @project.url@
    inception-year: @inceptionYear@
    organization-name: @project.organization.name@
    organization-url: @project.organization.url@
    issue-management-system: @project.issueManagement.system@
    issue-management-url: @project.issueManagement.url@
    developer-name: @developerName@
    developer-email: @developerEmail@
    developer-url: @developerUrl@
  configuration:
    ignored-url:
      pattern:
        - "/static/**"
        - "/actuator/**"
        - "/druid/**"
        - "/swagger-resources/**"
        - "/v2/api-docs/**"
        - "/*/v2/api-docs/**"
        - "/webjars/**"
        - "/doc.html"
    included-package-for-http-api-scan: ${project.property.base-package}
