eureka:
  client:
    serviceUrl:
      defaultZone: http://maf.service-registry.production:8760/eureka/

spring:
  zipkin:
    base-url: http://maf.open-zipkin.production:9411
  datasource:
    name: muscle_and_fitness
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://maf.mysql.production:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: root
    password: jm@mysql
  devtools:
    add-properties: false

maf:
  configuration:
    swagger-disabled: true
