eureka:
  client:
    serviceUrl:
      defaultZone: http://maf.service-registry.dev:8760/eureka/

spring:
  zipkin:
    base-url: http://maf.open-zipkin.dev:9411
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://maf.mysql.dev:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: root
    password: jm@mysql
  redis:
    host: maf.redis.dev
    port: 6379
    password: 123456

maf:
  configuration:
    swagger-disabled: false
