spring:
  zipkin:
    base-url: http://maf.zipkin.test:9411
  devtools:
    add-properties: false
  datasource:
    url: jdbc:mysql://maf.mysql-server.test:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: maf_mysql_rw
    password: maf@mysql
  redis:
    host: maf.redis.test
    port: 6379
    password: maf@redis
  rabbitmq:
    host: maf.rabbitmq.test
    port: 5672
    username: maf_rabbitmq_su
    password: maf@rabbitmq

sftp:
  client:
    configuration:
      host: maf.atmoz-sftp.test
      port: 22
      user: johnny
      password: atmoz@sftp

maf:
  configuration:
    swagger-disabled: true
