eureka:
  client:
    serviceUrl:
      defaultZone: http://maf.service-registry.stage:8760/eureka/

spring:
  zipkin:
    base-url: http://maf.open-zipkin.stage:9411
  datasource:
    name: muscle_and_fitness
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://maf.mysql.stage:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: root
    password: jm@mysql
  redis:
    database: 0
    host: maf.redis.stage
    port: 6379
    password: 123456
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: -1ms
        min-idle: 0
  devtools:
    add-properties: false

sftp:
  client:
    configuration:
      host: maf.atmoz-sftp.stage
      port: 22
      user: johnny
      password: atmoz@sftp
      directory: upload
      private-key:
      private-key-pass-phrase:
      session-cache-size: 20
      session-wait-timeout: 15000

maf:
  configuration:
    swagger-disabled: true
