spring:
  cloud:
    consul:
      host: maf.consul-service-registry.development
      port: 8500
  zipkin:
    base-url: http://maf.zipkin.development:9411
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://maf.mysql.development:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: root
    password: jm@mysql
  redis:
    host: maf.redis.development
    port: 6379
    password: 123456

sftp:
  client:
    configuration:
      host: maf.atmoz-sftp.development
      port: 22
      user: johnny
      password: atmoz@sftp

maf:
  configuration:
    swagger-disabled: false
