eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

spring:
  zipkin:
    base-url: http://localhost:9411
  datasource:
    name: muscle_and_fitness
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: root
    password: jm@mysql
  devtools:
    restart:
      enabled: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: -1ms
        min-idle: 0

logging:
  # Configure logging level for SFTP/JSCH
  level:
    com.jcraft.jsch: INFO

sftp:
  client:
    configuration:
      host: localhost
      port: 23
      user: johnny
      password: atmoz@sftp
      directory: upload
      private-key:
      private-key-pass-phrase:
      session-cache-size: 20
      session-wait-timeout: 15000
