server:
  port: @auth-center.port@
  tomcat:
    uri-encoding: @project.build.sourceEncoding@
  shutdown: GRACEFUL
  servlet:
    context-path:

spring:
  profiles:
    active: @env@
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Hong_Kong
  sleuth:
    sampler:
      probability: 1.0
  servlet:
    multipart:
      # `location` specifies the directory where uploaded files will be stored. When not specified,
      # a temporary directory will be used. ATTENTION: it may differ due to OS.
      location: ~/Documents/@project.parent.artifactId@/${spring.application.name}/temprary-file
      # `max-file-size` specifies the maximum size permitted for uploaded files. The default is 1MB. We set it as 64 MB.
      max-file-size: 64MB
      # `max-request-size` specifies the maximum size allowed for multipart/form-data requests. The default is 10MB.
      max-request-size: 70MB
      # `file-size-threshold` specifies the size threshold after which files will be written to disk.
      # The default is 0. We set it as 0 too.
      file-size-threshold: 0
  cloud:
    consul:
      discovery:
        register: true
        instance-id: ${spring.application.name}-${spring.cloud.client.hostname}-${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        service-name: ${spring.application.name}
        port: ${server.port}
        prefer-ip-address: true
        ip-address: ${spring.cloud.client.ip-address}
        health-check-critical-timeout: 15s
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      minIdle: 10
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      keep-alive: true
      filters: stat,wall,log4j2
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        slf4j:
          enabled: true
          statement-log-error-enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 1000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: root
        login-password: maf_druid_password
        allow:
  redis:
    database: 0
    timeout: 10000ms
    client-type: LETTUCE
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: -1ms
        min-idle: 0

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
  compression:
    request:
      enabled: true
    response:
      enabled: true
      useGzipDecoder: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mapper-locations should start with `classpath*` prefix
  # when project is based on Maven multi-module to load XML mapper in different jar
  mapper-locations: classpath*:/mapper/**/*Mapper.xml

logging:
  config: classpath:logback-configuration/logback-${spring.profiles.active}.xml
  level:
    # Configure logging level for SFTP/JSCH
    com.jcraft.jsch: INFO

maf:
  project-property:
    base-package: @project.groupId@
    context-path: ${server.servlet.context-path}
    group-id: @project.groupId@
    project-parent-artifact-id: @project.parent.artifactId@
    project-artifact-id: @project.artifactId@
    version: @project.version@
    description: @project.description@
    jdk-version: @java.version@
    environment: ${spring.profiles.active}
    url: @project.url@
    inception-year: @inceptionYear@
    organization-name: @project.organization.name@
    organization-url: @project.organization.url@
    issue-management-system: @project.issueManagement.system@
    issue-management-url: @project.issueManagement.url@
    developer-name: @developerName@
    developer-email: @developerEmail@
    developer-url: @developerUrl@
  configuration:
    ignored-url:
      pattern:
        - "/static/**"
        - "/actuator/**"
        - "/druid/**"
        - "/swagger-resources/**"
        - "/v2/api-docs/**"
        - "/*/v2/api-docs/**"
        - "/webjars/**"
        - "/doc.html"
    included-package-for-http-api-scan: ${maf.project-property.base-package}
    jwt:
      # an hour
      ttl: 3600000
