spring:
  cloud:
    consul:
      host: localhost
      port: 8500
  zipkin:
    base-url: http://localhost:9411
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://localhost:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: root
    password: jm@mysql
  redis:
    host: localhost
    port: 6379
    password: 123456

logging:
  # Configure logging level for SFTP/JSCH
  level:
    com.jcraft.jsch: INFO
    org.springframework.web: DEBUG

sftp:
  client:
    configuration:
      host: localhost
      port: 23
      user: johnny
      password: atmoz@sftp

maf:
  configuration:
    swagger-disabled: false
