spring:
  zipkin:
    base-url: http://localhost:9411
  devtools:
    add-properties: true
  datasource:
    dynamic:
      datasource:
        master_1:
          url: jdbc:mysql://localhost:3306/muscle_and_fitness?useSSL=true&useUnicode=true
          username: maf_mysql_rw
          password: maf@mysql
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://localhost:3307/muscle_and_fitness?useSSL=true&useUnicode=true
          username: maf_mysql_r
          password: maf@mysql
          driver-class-name: com.mysql.cj.jdbc.Driver
        quartz:
          url: jdbc:mysql://localhost:3306/QUARTZ_DB?useSSL=true&useUnicode=true
          username: maf_mysql_rw
          password: maf@mysql
          driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: maf_rabbitmq_su
    password: maf@rabbitmq

redis:
  master:
    host: localhost
    port: 6379
    password: maf@redis
  slaves:
    - host: localhost
      port: 6380
      password: maf@redis

logging:
  level:
    com.baomidou: DEBUG
    com.jmsoftware: DEBUG

maf:
  configuration:
    swagger-enabled: true

minio:
  endpoint: http://localhost
  port: 9900
  access-key: maf_minio_root_user
  secret-key: jm@minio
  bucket-name: maf
