server:
  port: @auth-center.port@
  #  servlet:
  #    context-path: /@project.artifactId@-@envAlias@
  tomcat:
    uri-encoding: @project.build.sourceEncoding@

spring:
  application:
    name: @project.artifactId@
  profiles:
    active: @env@
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  sleuth:
    sampler:
      probability: 1.0
  servlet:
    multipart:
      # `location` specifies the directory where uploaded files will be stored. When not specified,
      # a temporary directory will be used. ATTENTION: it may differ due to OS.
      location: /Users/johnny/Documents/@project.artifactId@/temprary-file
      # `max-file-size` specifies the maximum size permitted for uploaded files. The default is 1MB. We set it as 64 MB.
      max-file-size: 64MB
      # `max-request-size` specifies the maximum size allowed for multipart/form-data requests. The default is 10MB.
      max-request-size: 70MB
      # `file-size-threshold` specifies the size threshold after which files will be written to disk.
      # The default is 0. We set it as 0 too.
      file-size-threshold: 0

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
  compression:
    request:
      enabled: true
    response:
      enabled: true
      useGzipDecoder: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  # mapper-locations should start with `classpath*` prefix
  # when project is based on Maven multi-module to load XML mapper in different jar
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  global-config:
    db-config:
      table-prefix: t_

logging:
  config: classpath:configuration/logback/logback-@env@.xml
  # Configure logging level of project as DEBUG to enable SQL logging and other logging.
  level:
    com.jmsoftware: DEBUG

project:
  property:
    base-package: com.jmsoftware.authcenter
    context-path:
    group-id: @project.groupId@
    parent-artifact-id: @parent.artifactId@
    project-artifact-id: @project.artifactId@
    version: @project.version@
    description: @project.description@
    jdk-version: @java.version@
    environment: @env@
    environment-alias: @envAlias@
    url: @project.url@
    inception-year: @inceptionYear@
    organization-name: @project.organization.name@
    organization-url: @project.organization.url@
    issue-management-system: @project.issueManagement.system@
    issue-management-url: @project.issueManagement.url@
    developer-name: @developerName@
    developer-email: @developerEmail@
    developer-url: @developerUrl@

# Customize JWT configuration for development environment.
jwt:
  configuration:
    # an hour
    ttl: 3600000
    ttl-for-remember-me: 604800000
