eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

spring:
  zipkin:
    base-url: http://localhost:9411
  devtools:
    add-properties: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: -1ms
        min-idle: 0

custom:
  configuration:
    # Leave `allowed-application-list` empty
    allowed-application-list:
    super-user: "admin"
    # Make `web-security-disabled` equal to true to disable web security. We suggest you do not turn off web security
    # feature unless development environment.
    web-security-disabled: false
    # Disable web request information log
    web-request-log-disabled: false
    ignored-request:
      post:
        - "/authentication/**"
      get:
        - "/auth/check-username-uniqueness"
        - "/auth/check-email-uniqueness"
        - "/auth/validate-username/**"
        - "/user/get-avatar"
        - "/common/get-jwt"
      pattern:
        - "/actuator/**"
        - "/druid/**"
        - "/swagger-resources/**"
        - "/v2/api-docs/**"
