eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      # needed to trigger info and endpoint update after restart
      startup: ${random.int}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

custom:
  configuration:
    # Leave `allowed-application-list` empty
    allowed-application-list:
