eureka:
  client:
    serviceUrl:
      defaultZone: http://maf.service-registry.stage:8760/eureka/

spring:
  zipkin:
    base-url: http://maf.open-zipkin.stage:9411

custom:
  configuration:
    allowed-application-list:
      - api-portal
