eureka:
  client:
    serviceUrl:
      defaultZone: http://maf.service-registry.test:8760/eureka/

spring:
  zipkin:
    base-url: http://maf.open-zipkin.test:9411
  devtools:
    add-properties: false

custom:
  configuration:
    super-user: "admin"
    # Make `web-security-disabled` equal to true to disable web security. We suggest you do not turn off web security
    # feature unless development environment.
    web-security-disabled: false
    # Disable web request information log
    web-request-log-disabled: false
    ignored-request:
      post:
        - "/authentication/**"
      get:
        - "/favicon.ico"
        - "/auth/check-username-uniqueness"
        - "/auth/check-email-uniqueness"
        - "/auth/validate-username/**"
        - "/user/get-avatar"
        - "/common/get-jwt"
      pattern:
        - "/static/**"
        - "/actuator/**"
        - "/druid/**"
        - "/swagger-resources/**"
        - "/v2/api-docs/**"
        - "/**/v2/api-docs/**"
        - "/webjars/**"
        - "/doc.html"
