eureka:
  client:
    serviceUrl:
      defaultZone: http://maf.service-registry.test:8760/eureka/

spring:
  zipkin:
    base-url: http://maf.open-zipkin.test:9411
  devtools:
    add-properties: false

custom:
  configuration:
    allowed-application-list:
      - api-portal
