eureka:
  client:
    serviceUrl:
      defaultZone: http://maf.service-registry.dev_dkr:8760/eureka/

spring:
  zipkin:
    base-url: http://maf.open-zipkin.dev_dkr:9411

custom:
  configuration:
    allowed-application-list:
      - api-portal
