eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.3.20:8760/eureka/

spring:
  zipkin:
    base-url: http://172.16.3.13:9411

custom:
  configuration:
    allowed-application-list:
      - api-portal
