eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

spring:
  zipkin:
    base-url: http://localhost:9411

custom:
  configuration:
    # Leave `allowed-application-list` empty
    allowed-application-list:
