version: "3.8"

services:
  ################################################################################
  #                           Infrastructure Services                            #
  ################################################################################
  mysql-server:
    container_name: ${MYSQL_SERVER_CONTAINER_NAME}
    image: mysql/mysql-server:${MYSQL_SERVER_TAG}
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MAF_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MAF_MYSQL_DATABASE}
      MYSQL_USER: ${MAF_MYSQL_USER}
      MYSQL_PASSWORD: ${MAF_MYSQL_PASSWORD}
      TZ: ${MAF_TIMEZONE}
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - "~/docker-file-mapping/${MYSQL_SERVER_CONTAINER_NAME}:/var/lib/mysql"
      - ./script/mysql-init-script:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      muscle_and_fitness_network:

  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: redis:${REDIS_TAG}
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - "~/docker-file-mapping/${REDIS_CONTAINER_NAME}:/data"
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      TZ: ${MAF_TIMEZONE}
    command: "redis-server /usr/local/etc/redis/redis.conf"
    networks:
      muscle_and_fitness_network:

  atmoz-sftp:
    container_name: ${ATMOZ_SFTP_CONTAINER_NAME}
    image: atmoz/sftp:${ATMOZ_SFTP_TAG}
    ports:
      # mapping local machine's port 23 to container port 22
      - "23:22"
    restart: always
    volumes:
      - "~/docker-file-mapping/${ATMOZ_SFTP_CONTAINER_NAME}:/home/johnny/upload"
    environment:
      TZ: ${MAF_TIMEZONE}
    command: "johnny:atmoz@sftp:::upload"
    networks:
      muscle_and_fitness_network:

  rabbitmq:
    container_name: ${RABBITMQ_CONTAINER_NAME}
    hostname: ${RABBITMQ_CONTAINER_NAME}
    image: rabbitmq:${RABBITMQ_TAG}
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    volumes:
      - "~/docker-file-mapping/${RABBITMQ_CONTAINER_NAME}:/var/lib/rabbitmq"
      - ./plugin/rabbitmq/rabbitmq_delayed_message_exchange-3.8.9-0199d11c.ez:/plugins/rabbitmq_delayed_message_exchange-3.8.9-0199d11c.ez
      - ./plugin/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    environment:
      RABBITMQ_DEFAULT_USER: ${MAF_RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${MAF_RABBITMQ_PASSWORD}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      muscle_and_fitness_network:

  zipkin-mysql:
    container_name: ${ZIPKIN_MYSQL_CONTAINER_NAME}
    image: openzipkin/zipkin-mysql:${ZIPKIN_MYSQL_TAG}
    restart: always
    networks:
      muscle_and_fitness_network:

  zipkin-dependencies:
    container_name: ${ZIPKIN_DEPENDENCIES_CONTAINER_NAME}
    image: openzipkin/zipkin-dependencies:${ZIPKIN_DEPENDENCIES_TAG}
    entrypoint: crond -f
    environment:
      # Uncomment to see dependency processing logs
      ZIPKIN_LOG_LEVEL: DEBUG
      STORAGE_TYPE: mysql
      MYSQL_HOST: ${ZIPKIN_MYSQL_CONTAINER_NAME}
      MYSQL_USER: zipkin
      MYSQL_PASS: zipkin
    depends_on:
      zipkin-mysql:
        condition: service_healthy
    restart: always
    networks:
      muscle_and_fitness_network:

  zipkin:
    container_name: ${ZIPKIN_CONTAINER_NAME}
    image: openzipkin/zipkin:${ZIPKIN_TAG}
    depends_on:
      zipkin-mysql:
        condition: service_healthy
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      STORAGE_TYPE: mysql
      # Point the zipkin at the storage backend
      MYSQL_HOST: ${ZIPKIN_MYSQL_CONTAINER_NAME}
      MYSQL_USER: zipkin
      MYSQL_PASS: zipkin
      # Uncomment to enable request logging (TRACE shows query values)
      command: --logging.level.com.datastax.oss.driver.internal.core.tracker.RequestLogger=TRACE
      JAVA_OPTS: -Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
      TZ: ${MAF_TIMEZONE}
    # Uncomment to enable scribe
    # - SCRIBE_ENABLED=true
    # Uncomment to enable self-tracing
    # - SELF_TRACING_ENABLED=true
    # Uncomment to enable debug logging
    # - JAVA_OPTS=-Dlogging.level.zipkin2=DEBUG
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
      # Uncomment if you set SCRIBE_ENABLED=true
      # - 9410:9410
    restart: always
    networks:
      muscle_and_fitness_network:

  consul-service-registry:
    container_name: ${CONSUL_SERVICE_REGISTRY_CONTAINER_NAME}
    hostname: ${CONSUL_SERVICE_REGISTRY_CONTAINER_NAME}
    image: consul:${CONSUL_TAG}
    depends_on:
      zipkin:
        condition: service_healthy
    ports:
      - "8500:8500"
    restart: always
    volumes:
      - "~/docker-file-mapping/${CONSUL_SERVICE_REGISTRY_CONTAINER_NAME}:/consul/data"
    command: "agent -server -ui -disable-host-node-id -bootstrap-expect=1 -client=0.0.0.0"
    networks:
      muscle_and_fitness_network:

  elasticsearch:
    container_name: ${ELASTICSEARCH_CONTAINER_NAME}
    image: elasticsearch:${ELASTICSEARCH_TAG}
    ports:
      - "9200:9200"
    restart: always
    volumes:
      - "~/docker-file-mapping/${ELASTICSEARCH_CONTAINER_NAME}/plugins:/usr/share/elasticsearch/plugins"
      - "~/docker-file-mapping/${ELASTICSEARCH_CONTAINER_NAME}/data:/usr/share/elasticsearch/data"
    environment:
      cluster.name: elasticsearch
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
      ELASTIC_PASSWORD: ${MAF_ELASTICSEARCH_PASSWORD}
      xpack.security.enabled: "true"
    networks:
      muscle_and_fitness_network:

  logstash:
    container_name: ${LOGSTASH_CONTAINER_NAME}
    image: logstash:${LOGSTASH_TAG}
    links:
      # The Logstash configuration uses domain `es` to reach the elasticsearch service
      - elasticsearch:es
    depends_on:
      elasticsearch:
        condition: service_started
    ports:
      - "4560:4560"
    restart: always
    volumes:
      - ./config/logstash/logstash-maf.conf:/usr/share/logstash/pipeline/logstash.conf
      # - "~/docker-file-mapping/${LOGSTASH_CONTAINER_NAME}:/usr/share/logstash/config/logstash.yml"
    networks:
      muscle_and_fitness_network:

  kibana:
    container_name: ${KIBANA_CONTAINER_NAME}
    image: kibana:${KIBANA_TAG}
    depends_on:
      elasticsearch:
        condition: service_started
    ports:
      - "5601:5601"
    restart: always
    environment:
      elasticsearch.hosts: "http://${ELASTICSEARCH_CONTAINER_NAME}:9200"
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: ${MAF_ELASTICSEARCH_PASSWORD}
    networks:
      muscle_and_fitness_network:

  spring-boot-admin:
    container_name: ${SPRING_BOOT_ADMIN_CONTAINER_NAME}
    hostname: ${SPRING_BOOT_ADMIN_CONTAINER_NAME}
    image: ijohnnymiller/muscle-and-fitness-server.spring-boot-admin:${MAF_TAG}
    depends_on:
      mysql-server:
        condition: service_healthy
      redis:
        condition: service_started
      atmoz-sftp:
        condition: service_started
      consul-service-registry:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - "8761:8761"
    restart: always
    volumes:
      - "~/docker-file-mapping/${SPRING_BOOT_ADMIN_CONTAINER_NAME}:/logs"
    environment:
      JAVA_TOOL_OPTIONS: "${JAVA_TOOL_OPTIONS}"
      TZ: ${MAF_TIMEZONE}
    healthcheck:
      test: "wget localhost:8761/actuator/health -q -O - > /dev/null 2>&1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      muscle_and_fitness_network:

  ################################################################################
  #                     Microservice of Muscle and Fitness                       #
  ################################################################################
  #                              Business Service                                #
  #------------------------------------------------------------------------------#
  api-gateway:
    container_name: ${API_GATEWAY_CONTAINER_NAME}
    hostname: ${API_GATEWAY_CONTAINER_NAME}
    image: ijohnnymiller/muscle-and-fitness-server.api-gateway:${MAF_TAG}
    depends_on:
      mysql-server:
        condition: service_healthy
      redis:
        condition: service_started
      atmoz-sftp:
        condition: service_started
      consul-service-registry:
        condition: service_started
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "~/docker-file-mapping/${API_GATEWAY_CONTAINER_NAME}:/logs"
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
      TZ: ${MAF_TIMEZONE}
    healthcheck:
      test: "wget localhost:8080/actuator/health -q -O - > /dev/null 2>&1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      muscle_and_fitness_network:

  auth-center:
    container_name: ${AUTH_CENTER_CONTAINER_NAME}
    hostname: ${AUTH_CENTER_CONTAINER_NAME}
    image: ijohnnymiller/muscle-and-fitness-server.auth-center:${MAF_TAG}
    depends_on:
      redis:
        condition: service_started
      consul-service-registry:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: always
    volumes:
      - "~/docker-file-mapping/${AUTH_CENTER_CONTAINER_NAME}:/logs"
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
      TZ: ${MAF_TIMEZONE}
    healthcheck:
      test: "wget localhost:8800/actuator/health -q -O - > /dev/null 2>&1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      muscle_and_fitness_network:

  exercise-mis:
    container_name: ${EXERCISE_MIS_CONTAINER_NAME}
    hostname: ${EXERCISE_MIS_CONTAINER_NAME}
    image: ijohnnymiller/muscle-and-fitness-server.exercise-mis:${MAF_TAG}
    depends_on:
      mysql-server:
        condition: service_healthy
      redis:
        condition: service_started
      atmoz-sftp:
        condition: service_started
      consul-service-registry:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: always
    volumes:
      - "~/docker-file-mapping/${EXERCISE_MIS_CONTAINER_NAME}:/logs"
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
      TZ: ${MAF_TIMEZONE}
    healthcheck:
      test: "wget localhost:8801/actuator/health -q -O - > /dev/null 2>&1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      muscle_and_fitness_network:

  muscle-mis:
    container_name: ${MUSCLE_MIS_CONTAINER_NAME}
    hostname: ${MUSCLE_MIS_CONTAINER_NAME}
    image: ijohnnymiller/muscle-and-fitness-server.muscle-mis:${MAF_TAG}
    depends_on:
      mysql-server:
        condition: service_healthy
      redis:
        condition: service_started
      atmoz-sftp:
        condition: service_started
      consul-service-registry:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: always
    volumes:
      - "~/docker-file-mapping/${MUSCLE_MIS_CONTAINER_NAME}:/logs"
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
      TZ: ${MAF_TIMEZONE}
    healthcheck:
      test: "wget localhost:8802/actuator/health -q -O - > /dev/null 2>&1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      muscle_and_fitness_network:

networks:
  muscle_and_fitness_network:
    ipam:
      driver: default
