version: "3.7"

################################################################################
#                        ATTENTIONS of Docker Compose                          #
################################################################################
# 1. Pattern of 'container_name' must be:                                      #
#    [service-name]-[system-short-name]-[environment-alias]                    #
#    For instance, there is a 'MySQL service' for 'Muscle and Fitness Server', #
#    the 'container_name' must be: mysql-maf.dev.                              #
#    In Kubernetes, 'container_name' must not be set.                          #
# 2. ${TAG} is defined in file '.env'.                                         #
# 3. The differences between each environment docker-compose.yml:              #
#    Environmental suffix. There are 4 types of environmental suffix:          #
#       * '.dev'                                                               #
#       * '.test'                                                              #
#       * '.stage'                                                             #
#       * '.prod'                                                              #
# 4. Define timezone for environment variable: Asia/Hong_Kong                  #
# 5. Define 'depends_on' for service                                           #
################################################################################

services:
  ################################################################################
  #                      Middleware of Muscle and Fitness                        #
  ################################################################################
  mysql:
    container_name: maf.mysql.stage
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "jm@mysql"
      MYSQL_DATABASE: muscle_and_fitness
      TZ: Asia/Hong_Kong
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ~/docker-file-mapping/maf.mysql.stage:/var/lib/mysql
      - ./script/mysql-init-script:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      muscle_and_fitness_network:

  redis:
    container_name: maf.redis.stage
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ~/docker-file-mapping/maf.redis.stage:/data
      - ./script/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      TZ: Asia/Hong_Kong
    command: "redis-server /usr/local/etc/redis/redis.conf"
    networks:
      muscle_and_fitness_network:

  atmoz-sftp:
    container_name: maf.atmoz-sftp.stage
    image: atmoz/sftp:latest
    ports:
      - "23:22"
    restart: always
    volumes:
      - ~/docker-file-mapping/maf.atmoz-sftp.stage:/home/johnny/upload
    environment:
      TZ: Asia/Hong_Kong
    command: "johnny:atmoz@sftp:::upload"
    networks:
      muscle_and_fitness_network:

  zipkin-mysql:
    image: openzipkin/zipkin-mysql
    container_name: maf.zipkin-mysql.stage
    restart: always
    volumes:
      - ~/docker-file-mapping/maf.zipkin-mysql.stage:/mysql/data
    networks:
      muscle_and_fitness_network:

  zipkin-dependencies:
    image: openzipkin/zipkin-dependencies
    container_name: maf.zipkin-dependencies.stage
    entrypoint: crond -f
    environment:
      # Uncomment to see dependency processing logs
      ZIPKIN_LOG_LEVEL: DEBUG
      STORAGE_TYPE: mysql
      MYSQL_HOST: maf.zipkin-mysql.production
      MYSQL_USER: zipkin
      MYSQL_PASS: zipkin
    depends_on:
      zipkin-mysql:
        condition: service_healthy
    networks:
      muscle_and_fitness_network:

  open-zipkin:
    container_name: maf.open-zipkin.stage
    image: openzipkin/zipkin
    depends_on:
      zipkin-mysql:
        condition: service_healthy
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      STORAGE_TYPE: mysql
      # Point the zipkin at the storage backend
      MYSQL_HOST: maf.zipkin-mysql.stage
      MYSQL_USER: zipkin
      MYSQL_PASS: zipkin
      # Uncomment to enable request logging (TRACE shows query values)
      command: --logging.level.com.datastax.oss.driver.internal.core.tracker.RequestLogger=TRACE
      JAVA_OPTS: -Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
      TZ: Asia/Hong_Kong
    # Uncomment to enable scribe
    # - SCRIBE_ENABLED=true
    # Uncomment to enable self-tracing
    # - SELF_TRACING_ENABLED=true
    # Uncomment to enable debug logging
    # - JAVA_OPTS=-Dlogging.level.zipkin2=DEBUG
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
      # Uncomment if you set SCRIBE_ENABLED=true
      # - 9410:9410
    restart: always
    networks:
      muscle_and_fitness_network:

  ################################################################################
  #                     Microservice of Muscle and Fitness                       #
  ################################################################################
  #                            Infrastructure Service                            #
  #------------------------------------------------------------------------------#
  service-registry:
    container_name: maf.service-registry.stage
    image: "ijohnnymiller/muscle-and-fitness-server.service-registry:${TAG}"
    depends_on:
      mysql:
        condition: service_started
      redis:
        condition: service_started
      atmoz-sftp:
        condition: service_started
      open-zipkin:
        condition: service_healthy
    ports:
      - "8760:8760"
    restart: always
    volumes:
      - ~/docker-file-mapping/maf.logs:/logs
    environment:
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx128m -Dspring.profiles.active=production
      TZ: Asia/Hong_Kong
    networks:
      muscle_and_fitness_network:

  spring-boot-admin:
    container_name: maf.spring-boot-admin.stage
    image: "ijohnnymiller/muscle-and-fitness-server.spring-boot-admin:${TAG}"
    depends_on:
      service-registry:
        condition: service_started
    ports:
      - "8761:8761"
    volumes:
      - ~/docker-file-mapping/maf.logs:/logs
    environment:
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx128m -Dspring.profiles.active=production
      TZ: Asia/Hong_Kong
    networks:
      muscle_and_fitness_network:

  api-gateway:
    container_name: maf.api-gateway.stage
    image: "ijohnnymiller/muscle-and-fitness-server.api-gateway:${TAG}"
    depends_on:
      service-registry:
        condition: service_started
    restart: always
    volumes:
      - ~/docker-file-mapping/maf.logs:/logs
    environment:
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx128m -Dspring.profiles.active=production
      TZ: Asia/Hong_Kong
    networks:
      muscle_and_fitness_network:

  ################################################################################
  #                     Microservice of Muscle and Fitness                       #
  ################################################################################
  #                              Business Service                                #
  #------------------------------------------------------------------------------#
  auth-center:
    container_name: maf.auth-center.stage
    image: "ijohnnymiller/muscle-and-fitness-server.auth-center:${TAG}"
    depends_on:
      service-registry:
        condition: service_started
    restart: always
    volumes:
      - ~/docker-file-mapping/maf.logs:/logs
    environment:
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx128m -Dspring.profiles.active=production
      TZ: Asia/Hong_Kong
    networks:
      muscle_and_fitness_network:

  exercise-mis:
    container_name: maf.exercise-mis.stage
    image: "ijohnnymiller/muscle-and-fitness-server.exercise-mis:${TAG}"
    depends_on:
      service-registry:
        condition: service_started
    restart: always
    volumes:
      - ~/docker-file-mapping/maf.logs:/logs
    environment:
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx128m -Dspring.profiles.active=production
      TZ: Asia/Hong_Kong
    networks:
      muscle_and_fitness_network:

  muscle-mis:
    container_name: maf.muscle-mis.stage
    image: "ijohnnymiller/muscle-and-fitness-server.muscle-mis:${TAG}"
    depends_on:
      service-registry:
        condition: service_started
    restart: always
    volumes:
      - ~/docker-file-mapping/maf.logs:/logs
    environment:
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx128m -Dspring.profiles.active=production
      TZ: Asia/Hong_Kong
    networks:
      muscle_and_fitness_network:

################################################################################
#                       Network for Muscle and Fitness                         #
################################################################################
networks:
  muscle_and_fitness_network:
    ipam:
      driver: default
