greeting: "Hello, World! From Consul config center!"

maf:
  configuration:
    swagger:
      ignored-service-ids:
        - "consul"
        - "api-gateway"
        - "spring-boot-admin"
    redis-rate-limiter:
      replenish-rate: 1
      burst-capacity: 1
      requested-tokens: 1
