eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

spring:
  zipkin:
    base-url: http://localhost:9411
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://localhost:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: root
    password: jm@mysql
  redis:
    host: localhost
    port: 6379
    password: 123456

logging:
  level:
    com.jcraft.jsch: INFO

maf:
  configuration:
    swagger-disabled: false
