eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

spring:
  zipkin:
    base-url: http://localhost:9411
  datasource:
    name: muscle_and_fitness
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: root
    password: jm@mysql
  devtools:
    add-properties: true

logging:
  level:
    com.jcraft.jsch: INFO

maf:
  configuration:
    swagger-disabled: false
