eureka:
  client:
    serviceUrl:
      defaultZone: http://maf.service-registry.dev:8760/eureka/

spring:
  zipkin:
    base-url: http://maf.open-zipkin.dev:9411
  datasource:
    name: muscle_and_fitness
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://maf.mysql.dev:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: root
    password: jm@mysql

logging:
  # Configure logging level for SFTP/JSCH
  level:
    com.jcraft.jsch: INFO
