spring:
  zipkin:
    base-url: http://maf.zipkin.stage:9411
  devtools:
    add-properties: false
  datasource:
    url: jdbc:mysql://maf.mysql-server.stage:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: maf_mysql_rw
    password: maf@mysql
  redis:
    host: maf.redis.stage
    port: 6379
    password: 123456

sftp:
  client:
    configuration:
      host: maf.atmoz-sftp.stage
      port: 22
      user: johnny
      password: atmoz@sftp

maf:
  configuration:
    swagger-disabled: true
