eureka:
  client:
    serviceUrl:
      defaultZone: http://maf.service-registry.stage:8760/eureka/

spring:
  zipkin:
    base-url: http://maf.open-zipkin.stage:9411
  devtools:
    add-properties: false
  datasource:
    url: jdbc:mysql://maf.mysql.stage:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: root
    password: jm@mysql
  redis:
    host: maf.redis.stage
    port: 6379
    password: 123456

maf:
  configuration:
    swagger-disabled: true
