/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    implementation(project(":maf-mis-web"))
    implementation(project(":maf-mis-message"))
}

description = "Muscle and Fitness Server :: MAF MIS - Bootstrap"
