/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    implementation(project(":api-gateway-web"))
    implementation(project(":api-gateway-message"))
}

description = "Muscle and Fitness Server :: API Gateway - Bootstrap"
