spring:
  zipkin:
    base-url: http://localhost:9411
  devtools:
    add-properties: true

redis:
  master:
    host: localhost
    port: 6379
    password: maf@redis
  slaves:
    - host: localhost
      port: 6380
      password: maf@redis

minio:
  endpoint: http://localhost
  port: 9900
  access-key: maf_minio_root_user
  secret-key: jm@minio
  bucket-name: maf
