spring:
  zipkin:
    base-url: http://maf-zipkin:9411
  devtools:
    add-properties: false

redis:
  master:
    host: maf-redis-master
    port: 6379
    password: maf@redis
  slaves:
    - host: maf-redis-slave-1
      port: 6379
      password: maf@redis

minio:
  endpoint: http://maf-minio
  port: 9000
  access-key: maf_minio_root_user
  secret-key: jm@minio
  bucket-name: maf
