/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    implementation(project(":oss-center-web"))
    implementation(project(":oss-center-message"))
}

description = "Muscle and Fitness Server :: OSS Center - Bootstrap"
