spring:
  zipkin:
    base-url: http://maf-zipkin:9411
  devtools:
    add-properties: false
  datasource:
    dynamic:
      datasource:
        master_1:
          url: jdbc:mysql://maf-mysql-server-source:3306/muscle_and_fitness?useSSL=true&useUnicode=true
          username: maf_mysql_rw
          password: maf@mysql
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://maf-mysql-server-replica-1:3306/muscle_and_fitness?useSSL=true&useUnicode=true
          username: maf_mysql_r
          password: maf@mysql
          driver-class-name: com.mysql.cj.jdbc.Driver
        quartz:
          url: jdbc:mysql://maf-mysql-server-source:3306/QUARTZ_DB?useSSL=true&useUnicode=true
          username: maf_mysql_rw
          password: maf@mysql
          driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: maf-rabbitmq
    port: 5672
    username: maf_rabbitmq_su
    password: maf@rabbitmq

redis:
  master:
    host: maf-redis-master
    port: 6379
    password: maf@redis
  slaves:
    - host: maf-redis-slave-1
      port: 6379
      password: maf@redis

minio:
  endpoint: http://maf-minio
  port: 9000
  access-key: maf_minio_root_user
  secret-key: jm@minio
  bucket-name: maf

maf:
  configuration:
    swagger-enabled: true
