# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - 'master'
      - 'feature/**'
    paths-ignore:
      - '**.md'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
      DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up AdoptOpenJDK
        uses: actions/setup-java@v2.3.0
        with:
          java-version: '11.0.11'
          distribution: 'adopt-hotspot'
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw
      - name: Build with Maven
        run: ./mvnw clean install -V -q -DskipTests=true -Dmaven.javadoc.skip=true -Djib.to.auth.username=$DOCKER_HUB_USERNAME -Djib.to.auth.password=$DOCKER_HUB_PASSWORD
      - name: Display built artifacts
        run: |
          dir
          ls -R -l | grep -i ".jar$"

  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.3.0
        with:
          java-version: '11.0.10'
          distribution: 'adopt-hotspot'
      - name: Check Dependencies version with Versions Maven Plugin
        run: mvn versions:display-dependency-updates versions:display-parent-updates -f pom.xml
