# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - 'master'
      - 'feature/**'
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11.0.9
        uses: actions/setup-java@v2.3.0
        with:
          java-version: '11.0.10'
          distribution: 'adopt-hotspot'
      - name: Build with Maven
        run: mvn clean validate compile --batch-mode --show-version --quiet -DskipTests=true -f pom.xml

  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.3.0
        with:
          java-version: '11.0.10'
          distribution: 'adopt-hotspot'
      - name: Check Dependencies version with Versions Maven Plugin
        run: mvn versions:display-dependency-updates versions:display-parent-updates -f pom.xml
