# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
    paths-ignore:
      - '**.md'
      - '_config.yml'
  pull_request:
    branches:
      - 'main'

env:
  TEMURIN_VERSION: '17.0.7+7'

jobs:
  build-api-gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Gradle Build :: api-gateway"
        uses: ./.github/actions/gradle-submodule-build
        with:
          temurinVersion: ${{ env.TEMURIN_VERSION }}
          submodulePath: api-gateway
          dockerHubUsername: ${{ secrets.DOCKER_HUB_USERNAME }}
          dockerHubPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
  build-auth-center:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Gradle Build :: auth-center"
        uses: ./.github/actions/gradle-submodule-build
        with:
          temurinVersion: ${{ env.TEMURIN_VERSION }}
          submodulePath: auth-center
          dockerHubUsername: ${{ secrets.DOCKER_HUB_USERNAME }}
          dockerHubPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
  build-maf-mis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Gradle Build :: maf-mis"
        uses: ./.github/actions/gradle-submodule-build
        with:
          temurinVersion: ${{ env.TEMURIN_VERSION }}
          submodulePath: maf-mis
          dockerHubUsername: ${{ secrets.DOCKER_HUB_USERNAME }}
          dockerHubPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
  build-oss-center:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Gradle Build :: oss-center"
        uses: ./.github/actions/gradle-submodule-build
        with:
          temurinVersion: ${{ env.TEMURIN_VERSION }}
          submodulePath: oss-center
          dockerHubUsername: ${{ secrets.DOCKER_HUB_USERNAME }}
          dockerHubPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
  build-spring-boot-admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Gradle Build :: spring-boot-admin"
        uses: ./.github/actions/gradle-submodule-build
        with:
          temurinVersion: ${{ env.TEMURIN_VERSION }}
          submodulePath: spring-boot-admin
          dockerHubUsername: ${{ secrets.DOCKER_HUB_USERNAME }}
          dockerHubPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}

  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{env.TEMURIN_VERSION}}
          distribution: 'temurin'
          cache: 'gradle'
      - name: Grant Execution Permission for `gradlew`
        run: chmod +x gradlew
      - name: Check Dependencies Version with Gradle `com.github.ben-manes.versions` Plugin
        run: ./gradlew dependencyUpdates --no-daemon
