spring:
  datasource:
    url: jdbc:mysql://localhost:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: root
    password: jm@mysql
  devtools:
    add-properties: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

maf:
  configuration:
    swagger-disabled: false
