spring:
  devtools:
    add-properties: false
  datasource:
    url: jdbc:mysql://maf.mysql.production:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: root
    password: jm@mysql
  redis:
    host: maf.redis.production
    port: 6379
    password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://maf.service-registry.production:8760/eureka/

maf:
  configuration:
    swagger-disabled: true

sftp:
  client:
    configuration:
      host: maf.atmoz-sftp.production
      port: 22
      user: johnny
      password: atmoz@sftp
