spring:
  devtools:
    add-properties: false
  zipkin:
    base-url: http://maf.zipkin.production:9411
  datasource:
    url: jdbc:mysql://maf.mysql.production:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: maf_mysql_rw
    password: maf@mysql
  redis:
    host: maf.redis.production
    port: 6379
    password: 123456

maf:
  configuration:
    swagger-disabled: true

sftp:
  client:
    configuration:
      host: maf.atmoz-sftp.production
      port: 22
      user: johnny
      password: atmoz@sftp
