spring:
  devtools:
    add-properties: true
  zipkin:
    base-url: http://maf.zipkin.development-local:9411
  datasource:
    url: jdbc:mysql://maf.mysql.development-local:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: root
    password: jm@mysql
  redis:
    host: maf.redis.development-local
    port: 6379
    password: 123456

maf:
  configuration:
    swagger-disabled: false

sftp:
  client:
    configuration:
      host: maf.atmoz-sftp.development-local
      port: 22
      user: johnny
      password: atmoz@sftp
