spring:
  devtools:
    add-properties: false
  zipkin:
    base-url: http://maf-zipkin-stage:9411
  datasource:
    url: jdbc:mysql://maf-mysql-server-stage:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: maf_mysql_rw
    password: maf@mysql
  redis:
    host: maf-redis-stage
    port: 6379
    password: maf@redis
  rabbitmq:
    host: maf-rabbitmq-stage
    port: 5672
    username: maf_rabbitmq_su
    password: maf@rabbitmq

maf:
  configuration:
    swagger-disabled: true

sftp:
  client:
    configuration:
      host: maf-atmoz-sftp-stage
      port: 22
      user: johnny
      password: atmoz@sftp
