spring:
  devtools:
    add-properties: true
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:mysql://localhost:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: maf_mysql_rw
    password: maf@mysql
  redis:
    host: localhost
    port: 6379
    password: 123456

maf:
  configuration:
    swagger-disabled: false

sftp:
  client:
    configuration:
      host: localhost
      port: 23
      user: johnny
      password: atmoz@sftp
