spring:
    url: jdbc:mysql://maf.mysql.dev:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: root
    password: jm@mysql
  devtools:
    add-properties: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://maf.service-registry.dev:8760/eureka/

maf:
  configuration:
    swagger-disabled: false
