spring:
  datasource:
    url: jdbc:mysql://maf.mysql.stage:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: root
    password: jm@mysql
  devtools:
    add-properties: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://maf.service-registry.stage:8760/eureka/

maf:
  configuration:
    swagger-disabled: true
