spring:
  devtools:
    add-properties: false
  cloud:
    consul:
      host: maf.consul-service-registry.stage
      port: 8500
  zipkin:
    base-url: http://maf.zipkin.stage:9411
  datasource:
    url: jdbc:mysql://maf.mysql.stage:3306/muscle_and_fitness?useSSL=true&useUnicode=true
    username: root
    password: jm@mysql
  redis:
    host: maf.redis.stage
    port: 6379
    password: 123456

maf:
  configuration:
    swagger-disabled: true

sftp:
  client:
    configuration:
      host: maf.atmoz-sftp.stage
      port: 22
      user: johnny
      password: atmoz@sftp
